Feat: save StudentParticipation in database with real data
KTH/course-survey-integration-api pull request #30
Opened 2024-02-21 08:50 UTC by exacs

2024-02-21 10:25 UTC, jhsware requested changes
So much nicer when this was rebased!!!
Over all, great work as usual!
I have some comments.

2024-02-21 10:25 UTC, jhsware commented on packages/kopps-integration/__tests__/utils.spec.ts
> +    expect(getPeriods(round)).toStrictEqual([5, 1, 1, 1]);
Is there a benefit to using integer representation as return values for getPeriods?

I think we should change the output of getPeriods to enums P0-P5 so we can improve type safety.

2024-02-21 10:25 UTC, jhsware commented on packages/kopps-integration/src/index.ts
>        periods: getPeriods(roundInformation),
This property won't map to period enums when consumed since they are restricted to P0-P5.

2024-02-21 10:25 UTC, jhsware commented on packages/ug-integration/__tests__/index.integration.ts
> +    expect(teachers[0].startsWith("u1")).toEqual(true);
We can remove the test for teachers because it is a duplicate.

2024-02-21 10:25 UTC, jhsware commented on packages/ug-integration/__tests__/index.integration.ts
> +    const res = await getUgSchool("J");
We decided on using the format:
- EECS
- EECS/JA
Will it be confusing if we fetch school by "J"?

2024-02-21 10:25 UTC, jhsware commented on packages/ug-integration/__tests__/index.integration.ts
> +    expect(teachers[0].startsWith("u1")).toEqual(true);
I think we are missing similar tests for:
-  getUgCourseResponsible
- getUgTeachers

2024-02-21 10:25 UTC, jhsware commented on src/functions/ladok-events/paborjatUtbildningstillfalleEvent.ts
> +  getUgExaminers,
Should we harmonise naming?
- getUgCourseTeachers
- getUgCourseResponsible
- getUgCourseExaminers

2024-02-21 10:25 UTC, jhsware commented on src/functions/ladok-events/paborjatUtbildningstillfalleEvent.ts
> +  );
Finally! :D

2024-02-21 10:25 UTC, jhsware commented on src/functions/ladok-events/utils.ts
> +  return ugUser.filter((o): o is TUgUser => o !== undefined).map(_convert);
I think the return type "o is TUgUser" could be confusing since a filter function should evaluate "truthy".

2024-02-21 12:39 UTC, exacs commented on src/functions/ladok-events/utils.ts
> +  return ugUser.filter((o): o is TUgUser => o !== undefined).map(_convert);
That is a good point. `obj is T` is used in TypeScript for functions that return "booleans with type meaning".

```ts
// For example, if the function is declared separately:
function isNotUndefined(obj: number | undefined): obj is number {
  return obj !== undefined;
}

const arr1 = [1, 2, 3, undefined]; // arr1: number | undefined
const arr2 = arr1.filter(isNotUndefined); // We don't need to type-cast!
```

In this particular case, your option is more readable and doesn't make any difference, so I'll put it back!

2024-02-21 12:39 UTC, exacs commented on src/functions/ladok-events/paborjatUtbildningstillfalleEvent.ts
> +  getUgExaminers,
Can fix it!

2024-02-21 12:40 UTC, exacs commented on packages/ug-integration/__tests__/index.integration.ts
> +    expect(teachers[0].startsWith("u1")).toEqual(true);
I can fix!

2024-02-21 12:42 UTC, exacs commented on __integration__/LadokEvents/__snapshots__/paborjatUtbildningstillfalleEvent.integration.ts.snap
> +    "courseExaminers": {},
Yes, you are right!

2024-02-21 12:43 UTC, exacs commented on __fixtures__/entities/01_courseRound.json
>    "courseTeachers": [],
I agree! Actually, the openapi spec doesn't allow undefined/null values here so this is something I need to fix!

2024-02-21 12:45 UTC, exacs commented on packages/kopps-integration/__tests__/utils.spec.ts
> +    expect(getPeriods(round)).toStrictEqual([5, 1, 1, 1]);
I agree! See comment below: https://github.com/KTH/course-survey-integration-api/pull/30#discussion_r1497469735

2024-02-21 13:03 UTC, exacs commented on __integration__/LadokEvents/__snapshots__/paborjatUtbildningstillfalleEvent.integration.ts.snap
> +    "courseExaminers": {},
This file is generated automatically when doing integration tests. Now I need to find test data to make sure the tests go through correctly.

Will take a bit more of time to fix this

2024-02-21 13:18 UTC, jhsware commented on src/functions/ladok-events/utils.ts
> +  return ugUser.filter((o): o is TUgUser => o !== undefined).map(_convert);
I think we should throw an error in getUgUser because that would make sense: "we expected to get user X from UG but got nothing" and UG will be a good starting point for troubleshooting.

2024-02-22 17:28 UTC, jhsware commented
All root package tests are passing

2024-02-22 17:28 UTC, merged